name: Claude PR Creation
on:
  issue_comment:
    types: [created]  # Triggers when someone comments on an issue or PR
  pull_request_review_comment:
    types: [created]  # Triggers when someone comments on a PR review
  issues:
    types: [opened]   # Triggers when a new issue is created

jobs:
  create-pr:
    # Only run if the comment mentions @claude
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    environment: gh-actions
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffs

      - uses: anthropics/claude-code-action@beta
        with:
          # Pass the comment text as the prompt
          prompt: "${{ github.event.comment.body || github.event.issue.body }}"

          # Define which tools Claude can use
          allowed_tools:
            - "Bash(git status)"
            - "Bash(git log)"
            - "Bash(git show)"
            - "Bash(git blame)"
            - "Bash(git reflog)"
            - "Bash(git stash list)"
            - "Bash(git ls-files)"
            - "Bash(git branch)"
            - "Bash(git tag)"
            - "Bash(git diff)"
            
            # File exploration tools
            - "View"        # Read file contents
            - "GlobTool"    # Find files by pattern
            - "GrepTool"    # Search file contents
            - "BatchTool"   # Run multiple tools in parallel

          # Timeout setting (in minutes)
          timeout_minutes: 30

          # Your Anthropic API key (stored as a GitHub secret)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
