name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.13.0'

      - name: Install dependencies
        run: just deps

      - name: Run backend tests
        run: just test-backend

      - name: Run frontend tests
        run: just test-frontend

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            coverage/
            *.out
          retention-days: 5
